### ISSUE TITLE
Error in commit references unknown v${version}.tar.gz

### ISSUE THREAD

**Issue by mwbringmann** [power-ras/servicelog#1]
Error in recent commit produces the following error message for rpmbuild:

[root@RHEL8 servicelog]# rpmbuild -ba ~/rpmbuild/SPECS/servicelog.spec
error: Bad source: /root/rpmbuild/SOURCES/v1.1.15.tar.gz: No such file or directory
[root@RHEL8 servicelog]#

The commit includes the change,

-Source0: https://github.com/power-ras/servicelog.git
+Source0: https://github.com/power-ras/%{name}/archive/v%{version}.tar.gz

which should have been,

-Source0: https://github.com/power-ras/servicelog.git
+Source0: https://github.com/power-ras/%{name}/archive/servicelog-%{version}.tar.gz

to match the file generated by the 'make dist-gzip' operation.

**Comment by hegdevasant** [comment]
Thanks for the report. I will fix it next week.

-Vasant
